#Sex
("http://ffmodmenu.page.link/Anti-V")
("http://vxvault.net/URL_List.php")
("http://data.phishtank.com/data/online-valid.csv")
("https://mypornsnap.xyz/photos/")
("https://www.dni.gov/nctc/ftos/isis_fto.html")
("http://www.hailsatanfilm.com")
("https://www.gunsinternational.com")
("http://www.tekdefense.com/downloads/malware-samples/KUNKRNMALWARESAMPLE.rar")
